[Variables]
Bar_Opacity=ff
Bar_Width =1920
Bar_Height =30
Bar_OffsetX =0
Bar_OffsetY =0

Section_Height =40
Section_Padding = 12

Color_Scheme1 =EFEFEF
Color_Scheme2 =1A1A1A
Color_Scheme3 =454545
Color_Scheme4 =616161
Color_Scheme5 =72B3CC

Font_Face=MonteCarlo Fixed 12
Font_Face1=MonteCarlo Fixed 12
Font_Face2=ProggyTinyTT
Font_Size1=12
Font_Size2=12

Shadow=0
Translucent=0

DefaultAddedModules=volume,tray,time,music

